apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-model-repository
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  # storageClassName: 환경에 맞는 StorageClass 지정
  # storageClassName: nfs-client
