apiVersion: v1
kind: Service
metadata:
  name: triton-server
  labels:
    app: triton-server
spec:
  selector:
    app: triton-server
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 8001
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 8002
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
