apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "triton.fullname" . }}-config
  labels:
    {{- include "triton.labels" . | nindent 4 }}
data:
  # Triton 서버 기동 인수 목록 (참고용, Deployment에서 직접 주입)
  triton-args: |
    {{- range .Values.tritonArgs }}
    {{ . }}
    {{- end }}
